### ISSUE TITLE
Sidebar Active

### ISSUE THREAD

**Issue by marcelloinfoweb** [pratikborsadiya/vali-admin#9]
Sidebar menu ativo não fica marcado quando clica nos menus e submenus, sempre volta para o dashboard.

**Comment by pratikborsadiya** [comment]
Issue is fixed in pull request #6

**Comment by marcelloinfoweb** [comment]
I downloaded it from github and used it, but it does not fix when I click the menu, it always activates only the "Dashboard" menu.

**Comment by pratikborsadiya** [comment]
@marcelloinfoweb The theme is not programmed and the sidebar component being included in the theme is the same on every page that's why it's showing the dashboard menu active all the time. When you implement it in your project you will have to add active class to menu item based on your current page path to highlight related sidebar item. So the support to highlight the sidebar item is there but since this is just an HTML theme, there is no point in highlighting the sidebar items.

**Comment by marcelloinfoweb** [comment]
I love your work, please do not misunderstand me, but it's not quite like that, [check out this dashboard](https://github.com/esironal/dashgum-template), it's just like your files, only html, css and js, and its menu when click is fixed in the active.

**Comment by pratikborsadiya** [comment]
Hi @marcelloinfoweb,
The new release (2.0) indicates the active items in sidebar. :smile:
